SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PERSONA WHERE PERSONA.TIPO ='ALUMNO' ORDER BY PERSONA.APELLIDO1 ASC, PERSONA.APELLIDO2 ASC, PERSONA.NOMBRE ASC;
SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PERSONA WHERE PERSONA.TIPO ='ALUMNO' AND PERSONA.TELEFONO IS NULL;
SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PERSONA WHERE PERSONA.TIPO ='ALUMNO' AND YEAR(PERSONA.FECHA_NACIMIENTO) = 1999;
SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PERSONA WHERE PERSONA.TIPO ='PROFESOR' AND PERSONA.TELEFONO IS NULL AND PERSONA.NIF LIKE '%K';
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA, GRADO WHERE ASIGNATURA.ID_GRADO = GRADO.ID AND ASIGNATURA.CURSO = 3 AND ASIGNATURA.CUATRIMESTRE = 1 AND ASIGNATURA.ID_GRADO = 7;
SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE, DEPARTAMENTO.NOMBRE FROM PROFESOR INNER JOIN PERSONA ON PERSONA.ID = PROFESOR.ID_PROFESOR INNER JOIN DEPARTAMENTO ON DEPARTAMENTO.ID = PROFESOR.ID_DEPARTAMENTO ORDER BY PERSONA.APELLIDO1 ASC, PERSONA.APELLIDO2 ASC, PERSONA.NOMBRE ASC;
SELECT ASIGNATURA.NOMBRE, CURSO_ESCOLAR.ANYO_INICIO, CURSO_ESCOLAR.ANYO_FIN FROM ALUMNO_SE_MATRICULA_ASIGNATURA INNER JOIN PERSONA ON ALUMNO_SE_MATRICULA_ASIGNATURA.ID_ALUMNO = PERSONA.ID INNER JOIN ASIGNATURA ON ALUMNO_SE_MATRICULA_ASIGNATURA.ID_ASIGNATURA = ASIGNATURA.ID INNER JOIN CURSO_ESCOLAR ON ALUMNO_SE_MATRICULA_ASIGNATURA.ID_CURSO_ESCOLAR = CURSO_ESCOLAR.ID WHERE PERSONA.NIF = '26902806M';
SELECT DISTINCT(DEPARTAMENTO.NOMBRE) FROM ASIGNATURA, GRADO, PROFESOR, DEPARTAMENTO WHERE ASIGNATURA.ID_GRADO = GRADO.ID AND ASIGNATURA.ID_PROFESOR = PROFESOR.ID_PROFESOR AND PROFESOR.ID_DEPARTAMENTO = DEPARTAMENTO.ID AND GRADO.NOMBRE = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM ALUMNO_SE_MATRICULA_ASIGNATURA, CURSO_ESCOLAR, PERSONA WHERE ALUMNO_SE_MATRICULA_ASIGNATURA.ID_ALUMNO = PERSONA.ID AND ALUMNO_SE_MATRICULA_ASIGNATURA.ID_CURSO_ESCOLAR = CURSO_ESCOLAR.ID AND CURSO_ESCOLAR.ANYO_INICIO = 2018 AND CURSO_ESCOLAR.ANYO_FIN = 2019;

/*Resol les 6 següents consultes utilitzant les clàusules LEFT JOIN i RIGHT JOIN*/
SELECT DEPARTAMENTO.NOMBRE AS DEPARTAMENTO, PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PROFESOR RIGHT JOIN PERSONA ON PROFESOR.ID_PROFESOR = PERSONA.ID LEFT JOIN DEPARTAMENTO ON PROFESOR.ID_DEPARTAMENTO = DEPARTAMENTO.ID WHERE PERSONA.TIPO = 'PROFESOR' ORDER BY DEPARTAMENTO.NOMBRE, PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE ASC;
SELECT PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PROFESOR LEFT JOIN PERSONA ON PROFESOR.ID_PROFESOR = PERSONA.ID WHERE PROFESOR.ID_DEPARTAMENTO IS NULL;
SELECT DEPARTAMENTO.NOMBRE FROM PROFESOR RIGHT JOIN DEPARTAMENTO ON PROFESOR.ID_DEPARTAMENTO = DEPARTAMENTO.ID WHERE PROFESOR.ID_PROFESOR IS NULL;
SELECT PERSONA.ID, PERSONA.APELLIDO1, PERSONA.APELLIDO2, PERSONA.NOMBRE FROM PERSONA LEFT JOIN ASIGNATURA ON PERSONA.ID = ASIGNATURA.ID_PROFESOR WHERE PERSONA.TIPO = 'PROFESOR' AND ASIGNATURA.ID_PROFESOR IS NULL;
SELECT ASIGNATURA.NOMBRE FROM PERSONA RIGHT JOIN ASIGNATURA ON PERSONA.ID = ASIGNATURA.ID_PROFESOR WHERE ASIGNATURA.ID_PROFESOR IS NULL;
SELECT DISTINCT DEPARTAMENTO.NOMBRE AS DEPARTAMENTO FROM DEPARTAMENTO LEFT JOIN PROFESOR ON DEPARTAMENTO.ID = PROFESOR.ID_DEPARTAMENTO LEFT JOIN ASIGNATURA ON PROFESOR.ID_PROFESOR = ASIGNATURA.ID_PROFESOR WHERE ASIGNATURA.ID_PROFESOR IS NULL;

/*Consultes resum*/
SELECT COUNT(DISTINCT(NIF)) AS TOTAL_DE_ALUMNOS FROM PERSONA WHERE PERSONA.TIPO = 'ALUMNO';
SELECT COUNT(DISTINCT(NIF)) AS TOTAL_DE_ALUMNOS_1999 FROM PERSONA WHERE PERSONA.TIPO = 'ALUMNO' AND YEAR(FECHA_NACIMIENTO) = 1999;
SELECT DEPARTAMENTO.NOMBRE AS DEPARTAMENTO, COUNT(PROFESOR.ID_PROFESOR) AS NUMERO_PROFESORES FROM PROFESOR INNER JOIN DEPARTAMENTO ON DEPARTAMENTO.ID = PROFESOR.ID_DEPARTAMENTO GROUP BY DEPARTAMENTO.NOMBRE ORDER BY NUMERO_PROFESORES DESC;
SELECT DEPARTAMENTO.NOMBRE AS DEPARTAMENTO, COUNT(PROFESOR.ID_PROFESOR) AS NUMERO_PROFESORES FROM PROFESOR RIGHT JOIN DEPARTAMENTO ON DEPARTAMENTO.ID = PROFESOR.ID_DEPARTAMENTO GROUP BY DEPARTAMENTO.NOMBRE;
SELECT GRADO.NOMBRE AS GRADO, COUNT(ASIGNATURA.ID_GRADO) AS NUMERO_ASIGNATURAS FROM ASIGNATURA RIGHT JOIN GRADO ON GRADO.ID = ASIGNATURA.ID_GRADO GROUP BY GRADO.NOMBRE ORDER BY NUMERO_ASIGNATURAS DESC;
SELECT GRADO.NOMBRE AS GRADO, COUNT(ASIGNATURA.ID_GRADO) AS NUMERO_ASIGNATURAS FROM ASIGNATURA RIGHT JOIN GRADO ON GRADO.ID = ASIGNATURA.ID_GRADO GROUP BY GRADO.NOMBRE HAVING COUNT(ASIGNATURA.ID_GRADO) > 40 ORDER BY NUMERO_ASIGNATURAS DESC;
SELECT GRADO.NOMBRE, ASIGNATURA.TIPO, SUM(ASIGNATURA.CREDITOS) AS CREDITOS FROM GRADO LEFT JOIN ASIGNATURA ON ASIGNATURA.ID_GRADO = GRADO.ID GROUP BY GRADO.NOMBRE, ASIGNATURA.TIPO;
SELECT CURSO_ESCOLAR.ANYO_INICIO, COUNT(DISTINCT(ALUMNO_SE_MATRICULA_ASIGNATURA.ID_ALUMNO)) AS ALUMNOS_MATRICULADOS FROM CURSO_ESCOLAR LEFT JOIN ALUMNO_SE_MATRICULA_ASIGNATURA ON ALUMNO_SE_MATRICULA_ASIGNATURA.ID_CURSO_ESCOLAR = CURSO_ESCOLAR.ID GROUP BY CURSO_ESCOLAR.ANYO_INICIO;
SELECT PERSONA.ID, PERSONA.NOMBRE, PERSONA.APELLIDO1, PERSONA.APELLIDO2, COUNT(DISTINCT(ASIGNATURA.ID)) AS NUMERO_ASIGNATURAS FROM ASIGNATURA RIGHT JOIN PERSONA ON ASIGNATURA.ID_PROFESOR = PERSONA.ID WHERE PERSONA.TIPO = 'PROFESOR' GROUP BY PERSONA.ID ORDER BY NUMERO_ASIGNATURAS DESC;
SELECT * FROM PERSONA ORDER BY FECHA_NACIMIENTO DESC LIMIT 1;
SELECT PERSONA.ID, PERSONA.NOMBRE, PERSONA.APELLIDO1, PERSONA.APELLIDO2 FROM PERSONA LEFT JOIN ASIGNATURA ON PERSONA.ID = ASIGNATURA.ID_PROFESOR INNER JOIN PROFESOR ON PERSONA.ID = PROFESOR.ID_PROFESOR WHERE ASIGNATURA.ID_PROFESOR IS NULL;