-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 17:51:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP DATABASE IF EXISTS Pizzeria;
CREATE DATABASE Pizzeria CHARACTER SET utf8mb4;
USE Pizzeria;
-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Localidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Localidat` (
  `idLocalidat` INT NOT NULL,
  `Nom` VARCHAR(50) NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idLocalidat`),
  INDEX `Fk_idProvincia_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `Fk_idProvincia`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Pizzeria`.`Provincia` (`idProvincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(60) NOT NULL,
  `Cognom` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NULL,
  `Codig_postal` INT NULL,
  `Localitat` INT NOT NULL,
  `Provincia` INT NOT NULL,
  `Num_Telefon` INT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `FK_provincia_idx` (`Provincia` ASC) VISIBLE,
  INDEX `Fk_Localitat_idx` (`Localitat` ASC) VISIBLE,
  CONSTRAINT `FK_provincia`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Pizzeria`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Localitat`
    FOREIGN KEY (`Localitat`)
    REFERENCES `Pizzeria`.`Localidat` (`idLocalidat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Botiga` (
  `idBotiga` INT NOT NULL,
  `Adreça` VARCHAR(100) NOT NULL,
  `Codig_Postal` VARCHAR(10) NOT NULL,
  `idLocalitat` INT NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idBotiga`),
  INDEX `FK_Provincia_idx` (`idProvincia` ASC) VISIBLE,
  INDEX `FK_Localitat_idx` (`idLocalitat` ASC) VISIBLE,
  CONSTRAINT `FK_Provincias`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Pizzeria`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Localitats`
    FOREIGN KEY (`idLocalitat`)
    REFERENCES `Pizzeria`.`Localidat` (`idLocalidat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda` (
  `idComanda` INT NOT NULL AUTO_INCREMENT,
  `Data/Hora` DATETIME NOT NULL,
  `EntregaDomiciliBotiga` VARCHAR(45) NOT NULL,
  `Productes_tipo` INT NOT NULL,
  `PreuTotal` FLOAT NOT NULL,
  `idClient` INT NOT NULL,
  `idBotiga` INT NOT NULL,
  PRIMARY KEY (`idComanda`),
  INDEX `FK_ClientComanda_idx` (`idClient` ASC) VISIBLE,
  UNIQUE INDEX `Productes_tipo_UNIQUE` (`Productes_tipo` ASC) VISIBLE,
  UNIQUE INDEX `idBotiga_UNIQUE` (`idBotiga` ASC) VISIBLE,
  CONSTRAINT `FK_ClientComanda`
    FOREIGN KEY (`idClient`)
    REFERENCES `Pizzeria`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_botiga`
    FOREIGN KEY (`idBotiga`)
    REFERENCES `Pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Categoria_Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Categoria_Pizza` (
  `IdCategoria` INT NOT NULL,
  `Tipo_pizza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCategoria`),
  UNIQUE INDEX `Tipo_pizza_UNIQUE` (`Tipo_pizza` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Productes` (
  `idProductes` INT NOT NULL,
  `nom` ENUM('Hamburguesa', 'beguda', 'pizza') NOT NULL,
  `Descripcio` MEDIUMTEXT NULL,
  `Imatge` MEDIUMBLOB NULL,
  `Preu` FLOAT NULL,
  `idComanda` INT NULL,
  `idCategoria` INT NULL,
  PRIMARY KEY (`idProductes`),
  INDEX `Fk_tipoProducte_idx` (`idComanda` ASC) VISIBLE,
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `Fk_tipoProducte`
    FOREIGN KEY (`idComanda`)
    REFERENCES `Pizzeria`.`Comanda` (`idComanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Pizza`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Pizzeria`.`Categoria_Pizza` (`IdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Treballador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Treballador` (
  `idTreballador` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognom` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Telefon` VARCHAR(45) NULL,
  `Cuiner/repartidor` VARCHAR(45) NOT NULL,
  `BotigaId` INT NOT NULL,
  PRIMARY KEY (`idTreballador`),
  UNIQUE INDEX `BotigaId_UNIQUE` (`BotigaId` ASC) VISIBLE,
  CONSTRAINT `FK_BotigaTreballador`
    FOREIGN KEY (`BotigaId`)
    REFERENCES `Pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `NomTreballador` VARCHAR(45) NOT NULL,
  `DataEntrega` DATETIME NOT NULL,
  `TreballadorId` INT NOT NULL,
  PRIMARY KEY (`idEntrega`),
  UNIQUE INDEX `NomTreballador_UNIQUE` (`NomTreballador` ASC) VISIBLE,
  UNIQUE INDEX `TreballadorId_UNIQUE` (`TreballadorId` ASC) VISIBLE,
  CONSTRAINT `FK_treballadorEntrega`
    FOREIGN KEY (`TreballadorId`)
    REFERENCES `Pizzeria`.`Treballador` (`idTreballador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
